#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/runtime:3.1 AS base

ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_URLS=http://+:5000,https://+:5001
ENV DOTNET_USE_POLLING_FILE_WATCHER=false

WORKDIR /app
COPY ./ /app

EXPOSE 5000
EXPOSE 5001

CMD ["dotnet", "TestTarget.dll"]
